//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepairShop.Texts.SharedResources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarRepairShop.Texts.SharedResources.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Technology: 
        ///
        ///    - Windows Forms
        ///
        ///Programming Language: 
        ///
        ///    - C#
        ///
        ///MVP Architecture:
        ///
        ///    The application logic is separated from the user interface, allowing easy modifications without impacting the entire application.
        ///
        ///Testability:
        ///
        ///    All business logic within the application is covered by unit tests, enabling verification of all use cases and maintaining high code quality.
        ///
        ///Database: 
        ///
        ///    The application data is stored in a relational SQL database hosted on Microsoft Azure, providi [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string HomeTabAboutThisProject {
            get {
                return ResourceManager.GetString("HomeTabAboutThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu I would like to express my sincere gratitude to my supervisor, Dr. Wiktoria Kalus, for her invaluable support, dedication, and insightful guidance throughout the realization of this engineering project.
        ///
        ///I also wish to thank the entire RS-Code team for my development as a software developer..
        /// </summary>
        internal static string HomeTabAcknowledgements {
            get {
                return ResourceManager.GetString("HomeTabAcknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing changelog entries or changelog file coulnd&apos;t be found..
        /// </summary>
        internal static string HomeTabChangelogLoadFailed {
            get {
                return ResourceManager.GetString("HomeTabChangelogLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to open GitHub page. URL might be outdated or you have internet connection issues..
        /// </summary>
        internal static string HomeTabGitHubLoadFailed {
            get {
                return ResourceManager.GetString("HomeTabGitHubLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sources:
        ///
        ///- Icons: https://icons8.com/.
        /// </summary>
        internal static string HomeTabSources {
            get {
                return ResourceManager.GetString("HomeTabSources", resourceCulture);
            }
        }
    }
}
