//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepairShop.Texts.SharedResources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarRepairShop.Texts.SharedResources.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Technology: 
        ///
        ///    - Windows Forms
        ///
        ///Programming Language: 
        ///
        ///    - C#
        ///
        ///MVP Architecture:
        ///
        ///    The application logic is separated from the user interface, allowing easy modifications without impacting the entire application.
        ///
        ///Testability:
        ///
        ///    All business logic within the application is covered by unit tests, enabling verification of all use cases and maintaining high code quality.
        ///
        ///Database: 
        ///
        ///    The application data is stored in a relational SQL database hosted on Microsoft Azure, providi [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string HomeTabAboutThisProject {
            get {
                return ResourceManager.GetString("HomeTabAboutThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu I would like to express my sincere gratitude to my supervisor, Dr. Wiktoria Kalus, for her invaluable support, dedication, and insightful guidance throughout the realization of this engineering project.
        ///
        ///I also wish to thank the entire RS-Code team for my development as a software developer..
        /// </summary>
        internal static string HomeTabAcknowledgements {
            get {
                return ResourceManager.GetString("HomeTabAcknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing changelog entries or changelog file coulnd&apos;t be found..
        /// </summary>
        internal static string HomeTabChangelogLoadFailed {
            get {
                return ResourceManager.GetString("HomeTabChangelogLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to open GitHub page. URL might be outdated or you have internet connection issues..
        /// </summary>
        internal static string HomeTabGitHubLoadFailed {
            get {
                return ResourceManager.GetString("HomeTabGitHubLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sources:
        ///
        ///- Icons: https://icons8.com/.
        /// </summary>
        internal static string HomeTabSources {
            get {
                return ResourceManager.GetString("HomeTabSources", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Contractors.
        /// </summary>
        internal static string MainForm_Contractors {
            get {
                return ResourceManager.GetString("MainForm_Contractors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CRM.
        /// </summary>
        internal static string MainForm_CRM {
            get {
                return ResourceManager.GetString("MainForm_CRM", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing permissions to display the {0} tab!.
        /// </summary>
        internal static string MainForm_MissingPermissionsToOpenTab {
            get {
                return ResourceManager.GetString("MainForm_MissingPermissionsToOpenTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Services.
        /// </summary>
        internal static string MainForm_Services {
            get {
                return ResourceManager.GetString("MainForm_Services", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Users.
        /// </summary>
        internal static string MainForm_Users {
            get {
                return ResourceManager.GetString("MainForm_Users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warehouse.
        /// </summary>
        internal static string MainForm_Warehouse {
            get {
                return ResourceManager.GetString("MainForm_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to delete the user: {0} {1}?.
        /// </summary>
        internal static string UsersTab_AskToDeleteBody {
            get {
                return ResourceManager.GetString("UsersTab_AskToDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deleting user.
        /// </summary>
        internal static string UsersTab_AskToDeleteHeader {
            get {
                return ResourceManager.GetString("UsersTab_AskToDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Permission assignement failed!.
        /// </summary>
        internal static string UsersTab_CouldntAddPermissions {
            get {
                return ResourceManager.GetString("UsersTab_CouldntAddPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The field firstname and lastname can&apos;t be empty!.
        /// </summary>
        internal static string UsersTab_FirstNameAndSurnameCannotBeEmpty {
            get {
                return ResourceManager.GetString("UsersTab_FirstNameAndSurnameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing permissions to edit in this tab! Please contact someone with edit permissions in users tab to assign new permissions for you!.
        /// </summary>
        internal static string UsersTab_MissingPermissions {
            get {
                return ResourceManager.GetString("UsersTab_MissingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a user to delete..
        /// </summary>
        internal static string UsersTab_PleaseSelectPersonToDelete {
            get {
                return ResourceManager.GetString("UsersTab_PleaseSelectPersonToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a user to edit..
        /// </summary>
        internal static string UsersTab_PleaseSelectPersonToEdit {
            get {
                return ResourceManager.GetString("UsersTab_PleaseSelectPersonToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error accured while inserting new user!.
        /// </summary>
        internal static string UsersTab_UserAddingError {
            get {
                return ResourceManager.GetString("UsersTab_UserAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error accured while deleting selected user!.
        /// </summary>
        internal static string UsersTab_UserDeleteError {
            get {
                return ResourceManager.GetString("UsersTab_UserDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error accured while editing selected user!.
        /// </summary>
        internal static string UsersTab_UserEditError {
            get {
                return ResourceManager.GetString("UsersTab_UserEditError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User with this firstname and lastname exists already!.
        /// </summary>
        internal static string UsersTab_UserExists {
            get {
                return ResourceManager.GetString("UsersTab_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User {0} {1} has been added..
        /// </summary>
        internal static string UsersTab_UserHasBeenAdded {
            get {
                return ResourceManager.GetString("UsersTab_UserHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User has been deleted..
        /// </summary>
        internal static string UsersTab_UserHasBeenDeleted {
            get {
                return ResourceManager.GetString("UsersTab_UserHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User data has been updated..
        /// </summary>
        internal static string UsersTab_UserHasBeenEdited {
            get {
                return ResourceManager.GetString("UsersTab_UserHasBeenEdited", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User permissions from:.
        /// </summary>
        internal static string UsersTab_UsersPermissions {
            get {
                return ResourceManager.GetString("UsersTab_UsersPermissions", resourceCulture);
            }
        }
    }
}
