//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepairShop.Texts.SharedResources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarRepairShop.Texts.SharedResources.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name can&apos;t be empty!.
        /// </summary>
        internal static string ConsuambleMaterial_NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ConsuambleMaterial_NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The quanitity must be greater than 0!.
        /// </summary>
        internal static string ConsumableMaterial_CorrectMaterialQuantity {
            get {
                return ResourceManager.GetString("ConsumableMaterial_CorrectMaterialQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material type: {0} exists already!.
        /// </summary>
        internal static string ConsumableMaterial_MaterialExistsAlready {
            get {
                return ResourceManager.GetString("ConsumableMaterial_MaterialExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material type: {0} couldn&apos;t be added!.
        /// </summary>
        internal static string ConsumableMaterial_MaterialInsertError {
            get {
                return ResourceManager.GetString("ConsumableMaterial_MaterialInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully added new material type..
        /// </summary>
        internal static string ConsumableMaterial_MaterialInsertSuccess {
            get {
                return ResourceManager.GetString("ConsumableMaterial_MaterialInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please provide the material name!.
        /// </summary>
        internal static string ConsumableMaterial_ProvideMaterialName {
            get {
                return ResourceManager.GetString("ConsumableMaterial_ProvideMaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Provide new materails type name:.
        /// </summary>
        internal static string ConsumableMaterial_ProvideNewMaterialsName {
            get {
                return ResourceManager.GetString("ConsumableMaterial_ProvideNewMaterialsName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select the material type!.
        /// </summary>
        internal static string ConsumableMaterial_SelectMaterialType {
            get {
                return ResourceManager.GetString("ConsumableMaterial_SelectMaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brand.
        /// </summary>
        internal static string CRMForm_BrandColumn {
            get {
                return ResourceManager.GetString("CRMForm_BrandColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to change the task status to closed?.
        /// </summary>
        internal static string CRMForm_ConfirmClosureBody {
            get {
                return ResourceManager.GetString("CRMForm_ConfirmClosureBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Confirm operation..
        /// </summary>
        internal static string CRMForm_ConfirmClosureTitle {
            get {
                return ResourceManager.GetString("CRMForm_ConfirmClosureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to reopen this task?.
        /// </summary>
        internal static string CRMForm_ConfirmReOpenBody {
            get {
                return ResourceManager.GetString("CRMForm_ConfirmReOpenBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Confirm operation..
        /// </summary>
        internal static string CRMForm_ConfirmReOpenTitle {
            get {
                return ResourceManager.GetString("CRMForm_ConfirmReOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to leave the comment empty?.
        /// </summary>
        internal static string CRMForm_EmptyComment {
            get {
                return ResourceManager.GetString("CRMForm_EmptyComment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Engine capacity.
        /// </summary>
        internal static string CRMForm_EngineCapacityColumn {
            get {
                return ResourceManager.GetString("CRMForm_EngineCapacityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error!.
        /// </summary>
        internal static string CRMForm_Error {
            get {
                return ResourceManager.GetString("CRMForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fuel type.
        /// </summary>
        internal static string CRMForm_FuelTypeColumn {
            get {
                return ResourceManager.GetString("CRMForm_FuelTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu License plate.
        /// </summary>
        internal static string CRMForm_LicensePlateColumn {
            get {
                return ResourceManager.GetString("CRMForm_LicensePlateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mileage.
        /// </summary>
        internal static string CRMForm_MileageColumn {
            get {
                return ResourceManager.GetString("CRMForm_MileageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Model.
        /// </summary>
        internal static string CRMForm_ModelColumn {
            get {
                return ResourceManager.GetString("CRMForm_ModelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string CRMForm_NameColumn {
            get {
                return ResourceManager.GetString("CRMForm_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        /// </summary>
        internal static string CRMForm_No {
            get {
                return ResourceManager.GetString("CRMForm_No", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Price.
        /// </summary>
        internal static string CRMForm_PriceColumn {
            get {
                return ResourceManager.GetString("CRMForm_PriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Production year.
        /// </summary>
        internal static string CRMForm_ProductionYear {
            get {
                return ResourceManager.GetString("CRMForm_ProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Quantity.
        /// </summary>
        internal static string CRMForm_QuantityColumn {
            get {
                return ResourceManager.GetString("CRMForm_QuantityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a contractor..
        /// </summary>
        internal static string CRMForm_SelectContractor {
            get {
                return ResourceManager.GetString("CRMForm_SelectContractor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select at least one service..
        /// </summary>
        internal static string CRMForm_SelectService {
            get {
                return ResourceManager.GetString("CRMForm_SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a vehicle..
        /// </summary>
        internal static string CRMForm_SelectVehicle {
            get {
                return ResourceManager.GetString("CRMForm_SelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning..
        /// </summary>
        internal static string CRMForm_Warning {
            get {
                return ResourceManager.GetString("CRMForm_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        internal static string CRMForm_Yes {
            get {
                return ResourceManager.GetString("CRMForm_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close date.
        /// </summary>
        internal static string CRMTab_ColumnCloseDate {
            get {
                return ResourceManager.GetString("CRMTab_ColumnCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Completed.
        /// </summary>
        internal static string CRMTab_ColumnCompleted {
            get {
                return ResourceManager.GetString("CRMTab_ColumnCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Contractor.
        /// </summary>
        internal static string CRMTab_ColumnContractorFullName {
            get {
                return ResourceManager.GetString("CRMTab_ColumnContractorFullName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        internal static string CRMTab_ColumnDescription {
            get {
                return ResourceManager.GetString("CRMTab_ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task created by.
        /// </summary>
        internal static string CRMTab_ColumnMechanicFullName {
            get {
                return ResourceManager.GetString("CRMTab_ColumnMechanicFullName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Price.
        /// </summary>
        internal static string CRMTab_ColumnPrice {
            get {
                return ResourceManager.GetString("CRMTab_ColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Services.
        /// </summary>
        internal static string CRMTab_ColumnServices {
            get {
                return ResourceManager.GetString("CRMTab_ColumnServices", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Creation date.
        /// </summary>
        internal static string CRMTab_ColumnStartDate {
            get {
                return ResourceManager.GetString("CRMTab_ColumnStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Vehicle details.
        /// </summary>
        internal static string CRMTab_ColumnVehicleData {
            get {
                return ResourceManager.GetString("CRMTab_ColumnVehicleData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to delete the selected task?.
        /// </summary>
        internal static string CRMTab_DeleteConfirmOperationBody {
            get {
                return ResourceManager.GetString("CRMTab_DeleteConfirmOperationBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operation confirmation..
        /// </summary>
        internal static string CRMTab_DeleteConfirmOperationTitle {
            get {
                return ResourceManager.GetString("CRMTab_DeleteConfirmOperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully deleted the selected task..
        /// </summary>
        internal static string CRMTab_DeleteSuccess {
            get {
                return ResourceManager.GetString("CRMTab_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task deletion has failed!.
        /// </summary>
        internal static string CRMTab_DeleteTaskError {
            get {
                return ResourceManager.GetString("CRMTab_DeleteTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task service mappings deletion has failed!.
        /// </summary>
        internal static string CRMTab_DeleteTaskMappingsError {
            get {
                return ResourceManager.GetString("CRMTab_DeleteTaskMappingsError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You need to have Super-Admin rights for this action!.
        /// </summary>
        internal static string CRMTab_MissingSuperAdminPermissions {
            get {
                return ResourceManager.GetString("CRMTab_MissingSuperAdminPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This task is already closed. Do you want to open it in read-only mode?.
        /// </summary>
        internal static string CRMTab_ReadOnlyViewBody {
            get {
                return ResourceManager.GetString("CRMTab_ReadOnlyViewBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task completed..
        /// </summary>
        internal static string CRMTab_ReadOnlyViewTitle {
            get {
                return ResourceManager.GetString("CRMTab_ReadOnlyViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task creation has failed!.
        /// </summary>
        internal static string CRMTab_TaskInsertFailed {
            get {
                return ResourceManager.GetString("CRMTab_TaskInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully added new task..
        /// </summary>
        internal static string CRMTab_TaskInsertSuccess {
            get {
                return ResourceManager.GetString("CRMTab_TaskInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task services mapping failed!.
        /// </summary>
        internal static string CRMTab_TaskMappingsInsertFailed {
            get {
                return ResourceManager.GetString("CRMTab_TaskMappingsInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task data couldn&apos;t be updated!.
        /// </summary>
        internal static string CRMTab_UpdateError {
            get {
                return ResourceManager.GetString("CRMTab_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully updated the task data..
        /// </summary>
        internal static string CRMTab_UpdateSuccess {
            get {
                return ResourceManager.GetString("CRMTab_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Technology: 
        ///
        ///    - Windows Forms
        ///
        ///Programming Language: 
        ///
        ///    - C#
        ///
        ///MVP Architecture:
        ///
        ///    The application logic is separated from the user interface, allowing easy modifications without impacting the entire application.
        ///
        ///Testability:
        ///
        ///    All business logic within the application is covered by unit tests, enabling verification of all use cases and maintaining high code quality.
        ///
        ///Database: 
        ///
        ///    The application data is stored in a relational SQL database hosted on Microsoft Azure, providi [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string HomeTabAboutThisProject {
            get {
                return ResourceManager.GetString("HomeTabAboutThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu I would like to express my sincere gratitude to my supervisor, Dr. Wiktoria Kalus, for her invaluable support, dedication, and insightful guidance throughout the realization of this engineering project.
        ///
        ///I also wish to thank the entire RS-Code team for my development as a software developer..
        /// </summary>
        internal static string HomeTabAcknowledgements {
            get {
                return ResourceManager.GetString("HomeTabAcknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing changelog entries or changelog file coulnd&apos;t be found..
        /// </summary>
        internal static string HomeTabChangelogLoadFailed {
            get {
                return ResourceManager.GetString("HomeTabChangelogLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to open GitHub page. URL might be outdated or you have internet connection issues..
        /// </summary>
        internal static string HomeTabGitHubLoadFailed {
            get {
                return ResourceManager.GetString("HomeTabGitHubLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sources:
        ///
        ///- Icons: https://icons8.com/.
        /// </summary>
        internal static string HomeTabSources {
            get {
                return ResourceManager.GetString("HomeTabSources", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The database requires a restart. Please wait 30 to 60 seconds and try again..
        /// </summary>
        internal static string LoginForm_DatabaseNeedsToRestart {
            get {
                return ResourceManager.GetString("LoginForm_DatabaseNeedsToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The following errors occurred:.
        /// </summary>
        internal static string LoginForm_FollowingErrorsOccurred {
            get {
                return ResourceManager.GetString("LoginForm_FollowingErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid login or password..
        /// </summary>
        internal static string LoginForm_InvalidCredentials {
            get {
                return ResourceManager.GetString("LoginForm_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error occurred while retrieving the database key from the Azure service. Please contact the administrator!.
        /// </summary>
        internal static string LoginForm_LoggedOutFromAzureService {
            get {
                return ResourceManager.GetString("LoginForm_LoggedOutFromAzureService", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter your login and password..
        /// </summary>
        internal static string LoginForm_ProvideLoginAndPassword {
            get {
                return ResourceManager.GetString("LoginForm_ProvideLoginAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Contractors.
        /// </summary>
        internal static string MainForm_Contractors {
            get {
                return ResourceManager.GetString("MainForm_Contractors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CRM.
        /// </summary>
        internal static string MainForm_CRM {
            get {
                return ResourceManager.GetString("MainForm_CRM", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing permissions to display the {0} tab!.
        /// </summary>
        internal static string MainForm_MissingPermissionsToOpenTab {
            get {
                return ResourceManager.GetString("MainForm_MissingPermissionsToOpenTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Services.
        /// </summary>
        internal static string MainForm_Services {
            get {
                return ResourceManager.GetString("MainForm_Services", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Users.
        /// </summary>
        internal static string MainForm_Users {
            get {
                return ResourceManager.GetString("MainForm_Users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warehouse.
        /// </summary>
        internal static string MainForm_Warehouse {
            get {
                return ResourceManager.GetString("MainForm_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add new material type:.
        /// </summary>
        internal static string MaterialsTypesList_AddNewMaterialType {
            get {
                return ResourceManager.GetString("MaterialsTypesList_AddNewMaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to delete the material type: {0}?.
        /// </summary>
        internal static string MaterialsTypesList_DeleteConfirmationBody {
            get {
                return ResourceManager.GetString("MaterialsTypesList_DeleteConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete confirmation.
        /// </summary>
        internal static string MaterialsTypesList_DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("MaterialsTypesList_DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material type: {0} couldn&apos;t be deleted!.
        /// </summary>
        internal static string MaterialsTypesList_DeleteError {
            get {
                return ResourceManager.GetString("MaterialsTypesList_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material type {0} has been deleted..
        /// </summary>
        internal static string MaterialsTypesList_DeleteSuccess {
            get {
                return ResourceManager.GetString("MaterialsTypesList_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material type name couldn&apos;t been updated!.
        /// </summary>
        internal static string MaterialsTypesList_EditError {
            get {
                return ResourceManager.GetString("MaterialsTypesList_EditError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit material type name:.
        /// </summary>
        internal static string MaterialsTypesList_EditMaterial {
            get {
                return ResourceManager.GetString("MaterialsTypesList_EditMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to change the material type name from {0} to {1}?.
        /// </summary>
        internal static string MaterialsTypesList_EditMaterialConfirmationBody {
            get {
                return ResourceManager.GetString("MaterialsTypesList_EditMaterialConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name change.
        /// </summary>
        internal static string MaterialsTypesList_EditMaterialConfirmationTitle {
            get {
                return ResourceManager.GetString("MaterialsTypesList_EditMaterialConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material type name has been updated..
        /// </summary>
        internal static string MaterialsTypesList_EditSuccess {
            get {
                return ResourceManager.GetString("MaterialsTypesList_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The material type: {0} couldn&apos;t be added!.
        /// </summary>
        internal static string MaterialsTypesList_InsertError {
            get {
                return ResourceManager.GetString("MaterialsTypesList_InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The material type: {0} has been successfully added..
        /// </summary>
        internal static string MaterialsTypesList_InsertSuccess {
            get {
                return ResourceManager.GetString("MaterialsTypesList_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to save changes?.
        /// </summary>
        internal static string PermissionsForm_AskToSaveBody {
            get {
                return ResourceManager.GetString("PermissionsForm_AskToSaveBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Permission change confirmation.
        /// </summary>
        internal static string PermissionsForm_AskToSaveTitle {
            get {
                return ResourceManager.GetString("PermissionsForm_AskToSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Changes has been saved..
        /// </summary>
        internal static string PermissionsForm_ChangesSaved {
            get {
                return ResourceManager.GetString("PermissionsForm_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Display.
        /// </summary>
        internal static string PermissionsForm_DatagridviewColumnAllowDisplay {
            get {
                return ResourceManager.GetString("PermissionsForm_DatagridviewColumnAllowDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        internal static string PermissionsForm_DatagridviewColumnAllowEdit {
            get {
                return ResourceManager.GetString("PermissionsForm_DatagridviewColumnAllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tab.
        /// </summary>
        internal static string PermissionsForm_DatagridviewColumnPermissionTab {
            get {
                return ResourceManager.GetString("PermissionsForm_DatagridviewColumnPermissionTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Contractors.
        /// </summary>
        internal static string PermissionsForm_PermissionContractors {
            get {
                return ResourceManager.GetString("PermissionsForm_PermissionContractors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CRM.
        /// </summary>
        internal static string PermissionsForm_PermissionCRM {
            get {
                return ResourceManager.GetString("PermissionsForm_PermissionCRM", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Services.
        /// </summary>
        internal static string PermissionsForm_PermissionServices {
            get {
                return ResourceManager.GetString("PermissionsForm_PermissionServices", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string PermissionsForm_PermissionSettings {
            get {
                return ResourceManager.GetString("PermissionsForm_PermissionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Statistics.
        /// </summary>
        internal static string PermissionsForm_PermissionStatistics {
            get {
                return ResourceManager.GetString("PermissionsForm_PermissionStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Users.
        /// </summary>
        internal static string PermissionsForm_PermissionUsers {
            get {
                return ResourceManager.GetString("PermissionsForm_PermissionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warehouse.
        /// </summary>
        internal static string PermissionsForm_PermissionWarehouse {
            get {
                return ResourceManager.GetString("PermissionsForm_PermissionWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit service: {0}.
        /// </summary>
        internal static string ServicesForm_EditServiceTitle {
            get {
                return ResourceManager.GetString("ServicesForm_EditServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add new service.
        /// </summary>
        internal static string ServicesForm_NewServiceTitle {
            get {
                return ResourceManager.GetString("ServicesForm_NewServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service duration time can&apos;t be less than 1 hour!.
        /// </summary>
        internal static string ServicesForm_PleaseProvideServiceDurationTime {
            get {
                return ResourceManager.GetString("ServicesForm_PleaseProvideServiceDurationTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service name can&apos;t be empty!.
        /// </summary>
        internal static string ServicesForm_PleaseProvideServiceName {
            get {
                return ResourceManager.GetString("ServicesForm_PleaseProvideServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please provide service price!.
        /// </summary>
        internal static string ServicesForm_PleaseProvideServicePrice {
            get {
                return ResourceManager.GetString("ServicesForm_PleaseProvideServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warranty time can&apos;t be less than 0 months!.
        /// </summary>
        internal static string ServicesForm_PleaseProvideServiceWarrantyTime {
            get {
                return ResourceManager.GetString("ServicesForm_PleaseProvideServiceWarrantyTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service with this name exists already!.
        /// </summary>
        internal static string ServicesForm_ServiceWithThisNameExistsAlready {
            get {
                return ResourceManager.GetString("ServicesForm_ServiceWithThisNameExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu active.
        /// </summary>
        internal static string ServicesTab_Active {
            get {
                return ResourceManager.GetString("ServicesTab_Active", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to change service: {0} status?.
        /// </summary>
        internal static string ServicesTab_ConfirmServiceStatusChangeBody {
            get {
                return ResourceManager.GetString("ServicesTab_ConfirmServiceStatusChangeBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Status change confirmation..
        /// </summary>
        internal static string ServicesTab_ConfirmServiceStatusChangeTitle {
            get {
                return ResourceManager.GetString("ServicesTab_ConfirmServiceStatusChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cost.
        /// </summary>
        internal static string ServicesTab_CostHeaderText {
            get {
                return ResourceManager.GetString("ServicesTab_CostHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to delete the service: {0}?.
        /// </summary>
        internal static string ServicesTab_DeleteConfirmBody {
            get {
                return ResourceManager.GetString("ServicesTab_DeleteConfirmBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete confirmation..
        /// </summary>
        internal static string ServicesTab_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("ServicesTab_DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service couldn&apos;t be deleted!.
        /// </summary>
        internal static string ServicesTab_DeleteError {
            get {
                return ResourceManager.GetString("ServicesTab_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully deleted service..
        /// </summary>
        internal static string ServicesTab_DeleteSuccess {
            get {
                return ResourceManager.GetString("ServicesTab_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Estimated execution time [hours].
        /// </summary>
        internal static string ServicesTab_DurationHeaderText {
            get {
                return ResourceManager.GetString("ServicesTab_DurationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu inaktive.
        /// </summary>
        internal static string ServicesTab_Inactive {
            get {
                return ResourceManager.GetString("ServicesTab_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New service couldn&apos;t be added!.
        /// </summary>
        internal static string ServicesTab_InsertError {
            get {
                return ResourceManager.GetString("ServicesTab_InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully added new service..
        /// </summary>
        internal static string ServicesTab_InsertSuccess {
            get {
                return ResourceManager.GetString("ServicesTab_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing edit permissions for edit tab!.
        /// </summary>
        internal static string ServicesTab_MissingEditPermissions {
            get {
                return ResourceManager.GetString("ServicesTab_MissingEditPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string ServicesTab_NameHeaderText {
            get {
                return ResourceManager.GetString("ServicesTab_NameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a services first..
        /// </summary>
        internal static string ServicesTab_PleaseSelectService {
            get {
                return ResourceManager.GetString("ServicesTab_PleaseSelectService", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service: {0} status couldn&apos;t be changed!.
        /// </summary>
        internal static string ServicesTab_StatusChangeError {
            get {
                return ResourceManager.GetString("ServicesTab_StatusChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully update service: {0} status to: {1}..
        /// </summary>
        internal static string ServicesTab_StatusChangeSuccess {
            get {
                return ResourceManager.GetString("ServicesTab_StatusChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Active.
        /// </summary>
        internal static string ServicesTab_StatusHeaderText {
            get {
                return ResourceManager.GetString("ServicesTab_StatusHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service: {0} couldn&apos;t be edited!.
        /// </summary>
        internal static string ServicesTab_UpdateError {
            get {
                return ResourceManager.GetString("ServicesTab_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully updated the service..
        /// </summary>
        internal static string ServicesTab_UpdateSuccess {
            get {
                return ResourceManager.GetString("ServicesTab_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warranty [months].
        /// </summary>
        internal static string ServicesTab_WarrantyHeaderText {
            get {
                return ResourceManager.GetString("ServicesTab_WarrantyHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The change of the language will restart the app! Do you want to change the language?.
        /// </summary>
        internal static string SettingsTab_LanguageChangeConfirmationBody {
            get {
                return ResourceManager.GetString("SettingsTab_LanguageChangeConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language change confirmation..
        /// </summary>
        internal static string SettingsTab_LanguageChangeConfirmationTitle {
            get {
                return ResourceManager.GetString("SettingsTab_LanguageChangeConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The password can&apos;t be empty!.
        /// </summary>
        internal static string SettingsTab_PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("SettingsTab_PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to change your password?.
        /// </summary>
        internal static string SettingsTab_PasswordChangeConfirmationBody {
            get {
                return ResourceManager.GetString("SettingsTab_PasswordChangeConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password change confirmation..
        /// </summary>
        internal static string SettingsTab_PasswordChangeConfirmationTitle {
            get {
                return ResourceManager.GetString("SettingsTab_PasswordChangeConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your password couldn&apos;t be changed!.
        /// </summary>
        internal static string SettingsTab_PasswordChangeError {
            get {
                return ResourceManager.GetString("SettingsTab_PasswordChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your password has been changed..
        /// </summary>
        internal static string SettingsTab_PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("SettingsTab_PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The provided password to change is the same as the actual password!.
        /// </summary>
        internal static string SettingsTab_ProvidedCurrentPasswordOnPasswordChange {
            get {
                return ResourceManager.GetString("SettingsTab_ProvidedCurrentPasswordOnPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The password is too short! It has to contain at least 5 characters!.
        /// </summary>
        internal static string SettingsTab_ProvidedPasswordIsTooShort {
            get {
                return ResourceManager.GetString("SettingsTab_ProvidedPasswordIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Provide new password:.
        /// </summary>
        internal static string SettingsTab_ProvideNewPassword {
            get {
                return ResourceManager.GetString("SettingsTab_ProvideNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select language:.
        /// </summary>
        internal static string SettingsTab_SelectLanguage {
            get {
                return ResourceManager.GetString("SettingsTab_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to delete the user: {0} {1}?.
        /// </summary>
        internal static string UsersTab_AskToDeleteBody {
            get {
                return ResourceManager.GetString("UsersTab_AskToDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deleting user.
        /// </summary>
        internal static string UsersTab_AskToDeleteHeader {
            get {
                return ResourceManager.GetString("UsersTab_AskToDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string UsersTab_ColumnName {
            get {
                return ResourceManager.GetString("UsersTab_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Surname.
        /// </summary>
        internal static string UsersTab_ColumnSurname {
            get {
                return ResourceManager.GetString("UsersTab_ColumnSurname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Permission assignement failed!.
        /// </summary>
        internal static string UsersTab_CouldntAddPermissions {
            get {
                return ResourceManager.GetString("UsersTab_CouldntAddPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The field firstname and lastname can&apos;t be empty!.
        /// </summary>
        internal static string UsersTab_FirstNameAndSurnameCannotBeEmpty {
            get {
                return ResourceManager.GetString("UsersTab_FirstNameAndSurnameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Provided login is already in use!.
        /// </summary>
        internal static string UsersTab_LoginAlreadyInUse {
            get {
                return ResourceManager.GetString("UsersTab_LoginAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing permissions to edit in this tab! Please contact someone with edit permissions in users tab to assign new permissions for you!.
        /// </summary>
        internal static string UsersTab_MissingPermissions {
            get {
                return ResourceManager.GetString("UsersTab_MissingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a user to delete..
        /// </summary>
        internal static string UsersTab_PleaseSelectPersonToDelete {
            get {
                return ResourceManager.GetString("UsersTab_PleaseSelectPersonToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a user to edit..
        /// </summary>
        internal static string UsersTab_PleaseSelectPersonToEdit {
            get {
                return ResourceManager.GetString("UsersTab_PleaseSelectPersonToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error accured while inserting new user!.
        /// </summary>
        internal static string UsersTab_UserAddingError {
            get {
                return ResourceManager.GetString("UsersTab_UserAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login and Password field cannot be empty!.
        /// </summary>
        internal static string UsersTab_UserCredentialsDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("UsersTab_UserCredentialsDataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error accured while deleting selected user!.
        /// </summary>
        internal static string UsersTab_UserDeleteError {
            get {
                return ResourceManager.GetString("UsersTab_UserDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error accured while editing selected user!.
        /// </summary>
        internal static string UsersTab_UserEditError {
            get {
                return ResourceManager.GetString("UsersTab_UserEditError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User with this firstname and lastname exists already!.
        /// </summary>
        internal static string UsersTab_UserExists {
            get {
                return ResourceManager.GetString("UsersTab_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User {0} {1} has been added..
        /// </summary>
        internal static string UsersTab_UserHasBeenAdded {
            get {
                return ResourceManager.GetString("UsersTab_UserHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User has been deleted..
        /// </summary>
        internal static string UsersTab_UserHasBeenDeleted {
            get {
                return ResourceManager.GetString("UsersTab_UserHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User data has been updated..
        /// </summary>
        internal static string UsersTab_UserHasBeenEdited {
            get {
                return ResourceManager.GetString("UsersTab_UserHasBeenEdited", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User {0} {1}.
        /// </summary>
        internal static string UsersTab_UserInfoTitle {
            get {
                return ResourceManager.GetString("UsersTab_UserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User permissions from:.
        /// </summary>
        internal static string UsersTab_UsersPermissions {
            get {
                return ResourceManager.GetString("UsersTab_UsersPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All.
        /// </summary>
        internal static string WarehouseTab_All {
            get {
                return ResourceManager.GetString("WarehouseTab_All", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material name.
        /// </summary>
        internal static string WarehouseTab_DataGridViewColumnMaterialName {
            get {
                return ResourceManager.GetString("WarehouseTab_DataGridViewColumnMaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material type name.
        /// </summary>
        internal static string WarehouseTab_DataGridViewColumnMaterialTypeName {
            get {
                return ResourceManager.GetString("WarehouseTab_DataGridViewColumnMaterialTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Quantity.
        /// </summary>
        internal static string WarehouseTab_DataGridViewColumnQuantity {
            get {
                return ResourceManager.GetString("WarehouseTab_DataGridViewColumnQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material deleted..
        /// </summary>
        internal static string WarehouseTab_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("WarehouseTab_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material couldn&apos;t be deleted!.
        /// </summary>
        internal static string WarehouseTab_DeleteError {
            get {
                return ResourceManager.GetString("WarehouseTab_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you really want to delete the consuamble material:.
        /// </summary>
        internal static string WarehouseTab_DeleteMaterialBody {
            get {
                return ResourceManager.GetString("WarehouseTab_DeleteMaterialBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Removal confirmation.
        /// </summary>
        internal static string WarehouseTab_DeleteMaterialHeader {
            get {
                return ResourceManager.GetString("WarehouseTab_DeleteMaterialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu A new consumable material couldn&apos;t be added to the database!.
        /// </summary>
        internal static string WarehouseTab_InsertingMaterialError {
            get {
                return ResourceManager.GetString("WarehouseTab_InsertingMaterialError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Added new consumable material successfully..
        /// </summary>
        internal static string WarehouseTab_MaterialAddedSuccessfully {
            get {
                return ResourceManager.GetString("WarehouseTab_MaterialAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material edit {0}.
        /// </summary>
        internal static string WarehouseTab_MaterialEdit {
            get {
                return ResourceManager.GetString("WarehouseTab_MaterialEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edited consumable material successfully..
        /// </summary>
        internal static string WarehouseTab_MaterialUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("WarehouseTab_MaterialUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The consumable material couldn&apos;t be updated!.
        /// </summary>
        internal static string WarehouseTab_MaterialUpdateError {
            get {
                return ResourceManager.GetString("WarehouseTab_MaterialUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add new consumable material.
        /// </summary>
        internal static string WatehouseTab_AddConsuambleMaterial {
            get {
                return ResourceManager.GetString("WatehouseTab_AddConsuambleMaterial", resourceCulture);
            }
        }
    }
}
